---
# Defaults for OMV role
omv_repo: "deb [signed-by=/usr/share/keyrings/openmediavault-archive-keyring.gpg] http://packages.openmediavault.org/public/ sandworm main"
omv_key_url: "https://packages.openmediavault.org/public/archive.key"

# SSH access settings for OMV admin account
omv_ssh_user: "{{ ansible_user | default('tochi') }}"
omv_ssh_group: "_ssh"
omv_ssh_public_key: ""
omv_ssh_public_key_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/hp-z440.pub"
