$ANSIBLE_VAULT;1.1;AES256
35356366386530306663643033616638393230666161626162643763363232356333396631666366
3730653239373435326663386664613935363236316338340a393334333062303065653230333635
61653738346461383632663365656663373536323530626235376666326536356332333335316463
6330623664303161610a363365336366303438343762653061353930363461376332346333376236
33643532633634613032313164373530633430643066656532313238323839313234616161373638
30366264326432666435326635396636633761316265386130303365323432313464346531643534
30626235376531653462663163383331363038626139353537343066373563313031383836373036
36366364323533373766393035363136663132633639373266313237633634353562333962303935
39663266386438393336613731346337323032633636386435343466383262363936616237333165
37326563636664303230323738363933623336626133306638633034343637353230666665613664
35633763643963663131326662366332616130396265306332306238393636613932663163653264
32643333323231346163393834666661373339346464613338643938376436613831643739323765
63356461666538333130316565346635336130313935336230353166326436616134373263383566
39316538306138643661623765633732346137386565303265666433633732336339633935323661
65316134666263306561623834393361336134333231373530636637383965326462363063643566
36623733613663666463323136336363613264313362373836363466333031303866393431646161
66373038323732653636343464653938383462623534373063373338613761616334646464653832
3438393766306435646131343263333235613361366363363834
