---
galaxy_info:
  role_name: proxmox_backup
  author: tom1022
  description: Configure Proxmox VE backup storage and backup jobs via API
  license: MIT
  min_ansible_version: '2.9'

dependencies: []
